name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Set image tags
        id: prep
        run: |
          echo "IMAGE_BACKEND=ghcr.io/iyxyi/kube-todo-backend:latest" >> $GITHUB_ENV
          echo "IMAGE_FRONTEND=ghcr.io/iyxyi/kube-todo-frontend:latest" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_BACKEND }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.IMAGE_FRONTEND }}

      - name: Set up KinD cluster
        uses: helm/kind-action@v1.8.0
        with:
          version: v0.23.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Deploy to KinD
        run: |
          kubectl apply -f k8s/
        shell: bash


