name: Publish Monitoring Exports to GitHub Pages

on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed

permissions:
  contents: read        # for reading repository
  pages: write          # required for deploying Pages
  id-token: write       # required by deploy-pages@v4

jobs:
  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Upload artifact for GitHub Pages deployment
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./monitoring-exports

      # Step 2: Deploy artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
