name: Publish Monitoring Exports to GitHub Pages

on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed

jobs:
  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          name: monitoring-exports
          path: monitoring-exports

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./monitoring-exports
          publish_branch: gh-pages
          force_orphan: true
